#!/bin/bash
: ${ORION_URL:?Not found}
: ${DEVICE_ID:?Not found}
curl -siX DELETE \
  "$ORION_URL/v2/entities/urn:ngsi-ld:Device:$DEVICE_ID" \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /sakuraio'
